name: flake_check

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  flake-checks:
    name: flake_check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          install_url: https://nixos.org/nix/install
          extra_nix_config: |
            auto-optimise-store = true
            experimental-features = nix-command flakes

      - name: Run flake check and capture logs
        id: flake_check
        run: |
          LOG_FILE="flake_check.log"
          nix flake check > "$LOG_FILE" 2>&1 || true
          echo "flake_check_log=$(cat "$LOG_FILE" | jq -sR)" >> $GITHUB_OUTPUT

      - name: Run flake install and capture logs
        id: flake_install
        run: |
          LOG_FILE="flake_install.log"
          nix profile install . > "$LOG_FILE" 2>&1 || true
          echo "flake_install_log=$(cat "$LOG_FILE" | jq -sR)" >> $GITHUB_OUTPUT

      - name: Debug Logs
        run: |
          echo "Flake Check Log:"
          echo "$FLAKE_CHECK_LOG"
          echo "Flake Install Log:"
          echo "$FLAKE_INSTALL_LOG"

      - name: Send Telegram Notification
        if: always()
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          BRANCH_NAME="${{ github.ref_name }}"
          FLAKE_CHECK_LOG_ESCAPED=$(echo "$FLAKE_CHECK_LOG" | sed ':a;N;$!ba;s/\n/\\n/g')
          FLAKE_INSTALL_LOG_ESCAPED=$(echo "$FLAKE_INSTALL_LOG" | sed ':a;N;$!ba;s/\n/\\n/g')

          if [[ "${{ job.status }}" == "success" ]]; then
            MESSAGE="✅ Flake check for Rishabh5321/seanime-flake completed successfully on branch $BRANCH_NAME."
          else
            MESSAGE="❌ Flake check for Rishabh5321/seanime-flake failed on branch $BRANCH_NAME. Check GitHub Actions for details."
          fi

          # Truncate logs to fit Telegram's message limit (4096 characters)
          FLAKE_CHECK_LOG_TRUNCATED=$(echo "$FLAKE_CHECK_LOG_ESCAPED" | cut -c -2000)
          FLAKE_INSTALL_LOG_TRUNCATED=$(echo "$FLAKE_INSTALL_LOG_ESCAPED" | cut -c -2000)

          # Send the message with logs
          curl -s -X POST https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage \
            -d chat_id=$CHAT_ID \
            -d text="$MESSAGE%0A%0AFlake Check Log:%0A$FLAKE_CHECK_LOG_TRUNCATED%0A%0AFlake Install Log:%0A$FLAKE_INSTALL_LOG_TRUNCATED"